# Generated by Django 4.0.4 on 2022-08-19 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Servico',
        ),
    ]
